# Generated by Django 4.2.30 on 2026-08-05 21:58

import cameras.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnrecognizedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.UUIDField(db_index=True)),
                ('file', models.ImageField(upload_to='unrecognized/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('hidden', models.BooleanField(default=False)),
                ('ftp_username', models.CharField(blank=True, max_length=12, unique=True)),
                ('ftp_password', models.CharField(blank=True, max_length=12)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='cameras.location')),
            ],
            options={
                'ordering': ['location__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=cameras.models.camera_image_upload_to)),
                ('taken_at', models.DateTimeField(db_index=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cameras.camera')),
            ],
            options={
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['camera', '-taken_at'], name='cameras_ima_camera__024571_idx')],
            },
        ),
    ]
