# Generated by Django 4.2.30 on 2026-08-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['location__order', 'location__name', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='camera',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
