# Generated by Django 4.2.30 on 2026-08-06 04:30

import secrets
import string

from django.db import migrations, models

ALPHANUMERIC = string.ascii_letters + string.digits


def generate_credential(length=12):
    return "".join(secrets.choice(ALPHANUMERIC) for _ in range(length))


def backfill_dynamic_dns_credentials(apps, schema_editor):
    Location = apps.get_model("cameras", "Location")
    used_usernames = set(Location.objects.exclude(dynamic_dns_username="").values_list(
        "dynamic_dns_username", flat=True
    ))
    for location in Location.objects.filter(dynamic_dns_username=""):
        candidate = generate_credential()
        while candidate in used_usernames:
            candidate = generate_credential()
        used_usernames.add(candidate)
        location.dynamic_dns_username = candidate
        location.dynamic_dns_password = generate_credential()
        location.save(update_fields=["dynamic_dns_username", "dynamic_dns_password"])


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alter_camera_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dynamic_dns_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='dynamic_dns_password',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='location',
            name='dynamic_dns_username',
            field=models.CharField(blank=True, max_length=12, default=""),
        ),
        migrations.AddField(
            model_name='location',
            name='ip_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='last_known_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_dynamic_dns_credentials, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='location',
            name='dynamic_dns_username',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
