# Generated by Django 4.2.30 on 2026-08-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alter_camera_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dynamic_dns_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='dynamic_dns_password',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='location',
            name='dynamic_dns_username',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='ip_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='last_known_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
