# Generated by Django 5.2.17 on 2026-08-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_location_dynamic_dns_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='remote_pull_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='remote_pull_timeout',
            field=models.PositiveIntegerField(default=7, help_text='Request timeout, in seconds.'),
        ),
        migrations.AddField(
            model_name='camera',
            name='remote_pull_url',
            field=models.CharField(blank=True, help_text="The camera's own snapshot URL, e.g. http://10.0.0.3/cgi-bin/api.cgi?cmd=Snap&channel=1", max_length=500),
        ),
        migrations.AddField(
            model_name='camera',
            name='remote_pull_use_location_ddns',
            field=models.BooleanField(default=False, help_text="Replace the camera URL's hostname with the location's dynamic DNS IP before each pull."),
        ),
    ]
