# Generated by Django 5.2.17 on 2026-08-06 04:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_camera_remote_pull_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
