# Generated by Django 5.2.17 on 2026-08-06 05:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_alter_camera_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
