# Generated by Django 5.2.17 on 2026-08-06 05:19

import cameras.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_alter_camera_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField()),
                ('file', models.ImageField(upload_to=cameras.models.embed_image_upload_to)),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='embed_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='embed_sizes',
            field=models.CharField(blank=True, help_text='Comma-separated pixel widths to generate for embedding, e.g. 400,800,1200', max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(fields=('location', 'slug'), name='unique_camera_slug_per_location'),
        ),
        migrations.AddField(
            model_name='embedimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeds', to='cameras.image'),
        ),
        migrations.AddConstraint(
            model_name='embedimage',
            constraint=models.UniqueConstraint(fields=('image', 'width'), name='unique_embed_image_width'),
        ),
    ]
